table Plants

	column ID
		dataType: int64
		isUnique
		isKey
		isNullable: false
		formatString: 0
		summarizeBy: none
		sourceColumn: ID

	column Name
		dataType: string
		summarizeBy: none
		sourceColumn: Name

	column Region
		dataType: string
		summarizeBy: none
		sourceColumn: Region

	column Country
		dataType: string
		summarizeBy: none
		sourceColumn: Country

	column City
		dataType: string
		summarizeBy: none
		sourceColumn: City

	column Year
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: Year

	partition Plants = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents(DataFolder, [RelativePath="Plants.csv"]),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"Name", type text}, {"Region", type text}, {"Country", type text}, {"City", type text}, {"Year", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

