/// Physical equipment we operate on the plant floor; one row per unit. Use for the machines we run - location, maker, type. Equipment we run, not a product we sell. Joins to ProductionLog via DeviceID.
table Assets

	/// Surrogate equipment key (integer); internal join key. Use Name for equipment questions.
	column ID
		dataType: int64
		isHidden
		isUnique
		isKey
		isNullable: false
		formatString: 0
		summarizeBy: none
		sourceColumn: ID

	/// Device identifier string, e.g. 'pump-001'. Join key to Lines[DeviceID] and ProductionLog[DeviceID]; internal, use Name for equipment questions.
	column Device_Id
		dataType: string
		isHidden
		isUnique
		summarizeBy: none
		sourceColumn: Device_Id

	/// Equipment we operate on the floor, e.g. 'Gas Turbine C1'. Use for equipment questions - location, maker, type. A unit we run, not a product we sell. Partial-text match.
	column 'Asset Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Name

	/// Equipment category, e.g. 'IndustrialPump','GasTurbine'. Use to group or filter equipment by kind. Partial-text match.
	column type
		dataType: string
		summarizeBy: none
		sourceColumn: type

	/// aka Machines. Use this column for questions related to Machines. Maker of the equipment, e.g. 'Siemens'. Use to group or filter equipment by maker. Partial-text match.
	column Manufacturer
		dataType: string
		summarizeBy: none
		sourceColumn: Mfr

	/// Plant key (integer) where the asset is installed; joins to Plants[ID]. Internal; use Plants[Name].
	column PlantID
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: PlantID

	/// On-site area where the equipment sits within a plant, e.g. 'Floor-A'. Use for where-installed questions. Partial-text match.
	column Location
		dataType: string
		summarizeBy: none
		sourceColumn: Location

	partition Assets = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents(DataFolder, [RelativePath="Assets.csv"]),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"Device_Id", type text}, {"Name", type text}, {"type", type text}, {"Mfr", type text}, {"PlantID", Int64.Type}, {"Location", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

