/// Pre-aggregated daily sales: net revenue by customer and day. One row per customer-day. Lighter than Sales; use for quick revenue-by-customer/day totals when line detail is not needed.
table SalesSummary

	/// Day of the summarized sales (day grain). Relate to Date for trends.
	column Date
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: Date

		annotation UnderlyingDateTimeDataType = Date

	/// Customer the summarized sales belong to; matches Customers[Customer Name]. Partial-text match.
	column 'Customer Name'
		dataType: string
		summarizeBy: none
		sourceColumn: custName

	/// Total net sales revenue for that customer and day (currency, USD). Sum for revenue totals.
	column Amount
		dataType: double
		formatString: 0.00
		summarizeBy: sum
		sourceColumn: Amount

	partition SalesSummary = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents(DataFolder, [RelativePath="Sheet1.csv"]),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"custName", type text}, {"Amount", type number}}),
				    #"Filtered AsOf" = Table.SelectRows(#"Changed Type", each [Date] <= (if AsOfDate = null or Text.Trim(AsOfDate) = "" then Date.From(DateTimeZone.FixedLocalNow()) else Date.FromText(Text.Trim(AsOfDate))))
				in
				    #"Filtered AsOf"

	annotation PBI_ResultType = Table

